# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "03af34bbe967e7558fcebfe6bc374374"
name = "remix-app-template"
handle = "remix-app-template-6"
application_url = "https://authorities-performances-digest-bufing.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "khoi-test-pod-app.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://authorities-performances-digest-bufing.trycloudflare.com/auth/callback",
  "https://authorities-performances-digest-bufing.trycloudflare.com/auth/shopify/callback",
  "https://authorities-performances-digest-bufing.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
